name: metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: "0x697A756B69"
          filename: metrics.svg
          base: ""
          plugin_isocalendar: yes
          output_action: commit
          retries: 1
          retries_delay: 10
          retries_output_action: 1
          retries_delay_output_action: 10
          extras_css: |
            svg { filter: grayscale(1); }
            path[fill="#ebedf0"] { fill: #e6e6e6 !important; }
            path[fill="#9be9a8"] { fill: #b8b8b8 !important; }
            path[fill="#40c463"] { fill: #8c8c8c !important; }
            path[fill="#30a14e"] { fill: #636363 !important; }
            path[fill="#216e39"] { fill: #3d3d3d !important; }
